server.port=8086

spring.application.name=CART-SERVICE

#my.app.title=FROM LOCAL

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Link With Config Server
spring.config.import=optional:configserver:http://localhost:8888

#enable services actutor
management.endpoints.web.exposure.include=*

#link with admin server
spring.boot.admin.client.url=http://localhost:9999

#connect ms to zipkin 
#management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans

#100% acces of request 
#management.tracing.sampling.probability=1.0