#PORT
#server.port=8086

# ServiceId (app Name)
spring.application.name=CART-SERVICE

#Local data
#my.app.title=FROM LOCAL

#Link With Config Server
#spring.config.import=optional:configserver:http://localhost:8888

server.port = 8081

#provide eureka location 
eureka.client.service-url-defaultZone=http://localhost8761/eureka

#register with eureka
eureka.client.register-with-eureka=true

#enable fetching other ms# details
eureka.client.fetch-registry=true