spring.application.name=03SpringbootWebAppFormBasic

server.port=9090

#view resolver details
#--prefix must start with / and end with /

spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp