spring.application.name=SpringBootLoggingEx

logging.level.com.aniket.rest=trace

logging.pattern.console= %d : %c : %p---> %m %n

logging.file.name=logger/log.txt
logging.pattern.file=%d : %c : %p --> %M : %n